# Generated by Django 5.1.4 on 2025-01-21 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
    ]
