# Generated by Django 5.1.4 on 2025-01-21 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20250121_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='r_creator_id',
        ),
    ]
