# Generated by Django 5.1.4 on 2025-01-23 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_room_r_creator_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-r_date_created']},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='rm_message',
        ),
    ]
