# Generated by Django 5.1.4 on 2025-01-23 10:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_room_r_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='r_participants',
            field=models.ManyToManyField(blank=True, related_name='r_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
