# Generated by Django 5.1.4 on 2025-01-30 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_r_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-rm_date_created']},
        ),
    ]
